const WELCOME_PROJECTS = [
    { name: "Glitch QR", icon: '<img src="images/icons/qr-icon.svg" alt="QR">', url: "https://github.com/eisenbruch/qr-glitch", type: "QR Code Tool", learning: "Generate scannable QR codes with glitch visual effects like RGB shift and wave distortion" },
    { name: "Snark AI", icon: '<img src="https://snark-ai.com/apple-touch-icon.png" alt="Snark AI">', url: "https://snark-ai.com", type: "AI Email Service", learning: "Email bodyguard that intercepts hostile emails and crafts witty, sarcastic responses" },
    { name: "Nerktendo", icon: '<img src="https://nerktendo.com/apple-touch-icon.png" alt="Nerktendo">', url: "https://nerktendo.com", type: "Retro Portfolio", learning: "A playable portfolio and retro emulator with a video game aesthetic" },
    { name: "LinkPee", icon: '<img src="https://linkp.ee/apple-touch-icon.png" alt="LinkPee">', url: "https://linkp.ee", type: "Link-in-Bio Service", learning: "Free Linktree alternative for creating a single page with all your links" },
    { name: "Weather Worsener", icon: "🌧️", url: "https://nerktendo.com/weather-worsener", type: "Interactive Game", learning: "Climate awareness game where you control disasters and try to eradicate humanity" },
    { name: "DomainFlip", icon: '<img src="images/icons/domainflip-icon.svg" alt="DomainFlip">', url: "https://nerktendo.com/domainflip", type: "Startup Demo", learning: "A polished demo platform for trading premium domains instantly" },
    { name: "TrafficVision", icon: '<img src="https://trafficvision.live/android-chrome-512x512.png" alt="TrafficVision">', url: "https://trafficvision.live", type: "Map & Database", learning: "Directory of 135,000+ live traffic cameras with real-time feeds from around the globe" },
    { name: "CamGuessr", icon: '<img src="images/icons/camguessr-icon.svg" alt="CamGuessr">', url: "https://trafficvision.live/camguessr", type: "Browser Game", learning: "GeoGuessr-style game where you guess locations from live traffic camera feeds" },
];

const WORKSHOP_PROJECTS = [
    { name: "The Playa Provides", author: "Ben Von Wong", url: "https://www.theplayaprovides.com/", type: "Community Tool", desc: "A circular economy platform for the Burning Man community to gift or lend gear and reduce waste" },
    { name: "Shuffleboard Jam", author: "Jeff Ziev", url: "https://shuffleboardjam.com", type: "Multiplayer Game", desc: "Online multiplayer shuffleboard videogame inspired by the Royal Palms Shuffleboard Club league" },
    { name: "ZigZag Explorer", author: "Ben Von Wong", url: "https://zigzag-explorer-vw.web.app/", type: "Star Wars", desc: "A non-linear journey through the Star Wars universe — explore characters, planets, and lore through an unconventional zigzag navigation pattern" },
    { name: "Surrender", author: "Ben Von Wong", url: "https://hope-surrender-vw.web.app/", type: "Personal", desc: "A journey back to us — an intimate, reflective experience exploring themes of reconciliation and reconnection" },
    { name: "The 3rd Door Brooklyn", author: "Ben Von Wong", url: "https://third-door-fundraiser.web.app/", type: "Concept / Fundraising", desc: "Concept site built in 15 minutes for a donation-based yoga & arts studio in DUMBO — showcases community loans and a solidarity fund" },
    { name: "Dune: Imperium Strategy Guide", author: "Ben Von Wong", url: "https://dune-strategy-guide.web.app/", type: "Board Games", desc: "Interactive strategy companion for the board game — select your player count, pick a leader, and get personalized recommendations" },
    { name: "Coach Pocket Guide to NYC", author: "Michelle Bernabe", url: "https://coach-pocket-nyc.web.app/", type: "Travel Guide", desc: "A pocket-sized travel guide to New York City" },
    { name: "RHV Universe", author: "Michelle Bernabe", url: "https://rhv-universe.surge.sh/", type: "Data Visualization", desc: "Interactive archive visualizing 500+ episodes of a healthcare podcast — spiral networks, topic maps, and language evolution across 12 years" },
    { name: "Ye Olde Hobby Finder", author: "Group Project", url: "https://workshop.nerktek.com/workshop-projects/2025-12-12-resistor/group-project-hobby-finder/hobby-finder.html", type: "Interactive Tool", desc: "Medieval-themed hobby discovery with Tinder-style swiping and head-to-head duels" },
    { name: "MJPEG Glitch Stream", author: "Noah", url: "https://workshop.nerktek.com/workshop-projects/2025-11-15-resistor/noah-eisenbruch-live-mjpeg-compression/index.html", type: "Webcam Tool", desc: "Live webcam feed with compression control and glitch effects like pixel sorting" },
    { name: "Top or Bottom?", author: "Hank", url: "https://workshop.nerktek.com/workshop-projects/2025-11-15-resistor/hank-top-or-bottom/index.html", type: "Parody Quiz", desc: "Quiz styled after early 2000s magazine flowcharts" },
    { name: "Band Tier Console", author: "Andy", url: "https://workshop.nerktek.com/workshop-projects/2025-11-15-resistor/andy-listing-thing/index.html", type: "Ranking Tool", desc: "Drag-and-drop ranking interface with cyberpunk aesthetic" },
];
